### ISSUE TITLE
PUID and PGID for docker compose

### ISSUE THREAD

**Issue by adepiero** [GregYankovoy/docker-goaccess#21]
Hello there.
I would like to run the container with no root privileges, using the same UID/GID of the nginx proxy manager container, so there would be no issues accessing log files.
I am not able to find the correct docker-compose.yml file syntax. I receive no errors when rebuilding the docker app, but a "ps- ef" shows me that the goaccess container is still running in the root context.
This is my docker compose service config for goaccess:
```
  goaccess:
    image: gregyankovoy/goaccess
    container_name: goaccess
    restart: unless-stopped
    ports:
      - '7889:7889'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./nginx-proxy-manager/log:/opt/log
      - ./goaccess:/config:rw
```
